supplier_homepage:
    pattern:  /
    defaults: { _controller: SupplierBundle:Default:index }

supplier_productData:
    pattern:  /dataGrid
    defaults: { _controller: SupplierBundle:Default:productData }
