parameters:
#    supplier.example.class: Biruwon\SupplierBundle\Example

services:
#    supplier.example:
#        class: %supplier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
