<?php

namespace Biruwon\SupplierBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
	public function getMAXandMIXDates()
	{
		$query = $this->getEntityManager()->createQuery(
			'SELECT
			    MAX(o.createdAt) as maxDate,
                MIN(o.createdAt) as minDate
            FROM SupplierBundle:Order o'
		    );

		return $query->getSingleResult();
	}
}
